exec = skib.exe
sources = $(wildcard src/*.c)
objects = $(sources:.c=.o)
flags = -g

$(exec): $(objects)
	gcc $(objects) $(flags) -o $(exec)

%.o: %.c include/%.h
	gcc -c $(flags) $< -o $@

clean:
	del /F /Q *.o *.exe skib skib.out 2>nul
	del /F /Q src\*.o 2>nul
